version: '3.8'
services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.14
    ports:
      - "443:443"
    volumes:
      - ./html:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/virtual-servers:/etc/nginx/conf.d/virtual-servers
      - /etc/localtime:/etc/localtime
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.1
    restart: always
    container_name: dev_nginx

  web74:
    image: orangehrm/orangehrm-environment-images:dev-7.4-centos-orange
    volumes:
    - ./html:/var/www/html
    - /etc/localtime:/etc/localtime
    sysctls:
    - kernel.shmmax=67371264
    networks:
    - ohrmdevnet
    restart: always
    container_name: dev_web_74

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
    - /etc/localtime:/etc/localtime
    environment:
      PMA_HOSTS: db10422
    networks:
      ohrmdevnet:
        ipv4_address: 10.5.2.2
    restart: always
    container_name: dev_phpmyadmin

networks:
  ohrmdevnet:
    driver: bridge
